"""categories autoincrement

Revision ID: f790e3f09c45
Revises: 2f6c8b1a4d93
Create Date: 2026-06-17 11:33:20.381251

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f790e3f09c45"
down_revision: Union[str, Sequence[str], None] = "2f6c8b1a4d93"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
